[tox]
envlist = standalone
skip_missing_interpreters = true

[testenv:standalone]
description = Build a PyInstaller executable for the current platform.
skip_install = true
deps =
    .[standalone]
commands =
    python scripts/build_executable.py
